version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante_db
      MYSQL_USER: restaurante_user
      MYSQL_PASSWORD: restaurante_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: restaurante_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # Aguarda MySQL estar pronto antes de iniciar a aplicação
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurante_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: restaurante_user
      SPRING_DATASOURCE_PASSWORD: restaurante_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"
    networks:
      - app_network
    entrypoint: ["sh", "-c", "echo 'Aguardando MySQL...' && sleep 20 && java -jar app.jar"]

volumes:
  mysql_data:

networks:
  app_network:
