spring:
  datasource:
    url: jdbc:mysql://mysql:3306/restaurante_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: restaurante_user
    password: restaurante_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always # Permite rodar scripts de inicialização no banco
